kind: Deployment
apiVersion: apps/v1
metadata:
  name: 300481-de
  namespace: 300481-de
  labels:
    app: 300481-de
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 300481-de
  template:
    metadata:
      labels:
        app: 300481-de
    spec:
      containers:
        - name: 300481-de
          image: 'ghcr.io/300481/300481.de:v0.0.4'
          resources:
            requests:
              memory: "4Mi"
              cpu: "100m"
            limits:
              memory: "32Mi"
              cpu: "200m"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
