kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: 300481-de
  namespace: 30481-de
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-modsecurity: 'true'
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: 'true'
spec:
  tls:
    - hosts:
        - 300481.de
      secretName: 300481-de-tls
  rules:
    - host: 300481.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-300481-de
                port:
                  number: 80

